name: the_hill_residence
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  change_app_package_name: ^1.0.0
  flutter_spinkit: "^5.1.0"
  font_awesome_flutter: ^9.2.0
  syncfusion_flutter_datepicker: ^19.4.54
  flutter_holo_date_picker: ^1.0.3
  image_stack: ^2.1.1
  overlay_support: ^2.1.0
  circular_countdown_timer: ^0.2.1
  auto_size_text: ^3.0.0
  fluttercontactpicker: ^4.7.0
  webview_flutter: ^3.0.4
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  google_sign_in: ^5.4.2
  open_mail_app: ^0.4.5
  whatsapp_share2: ^2.0.2
  share_plus: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/images/
    - assets/html/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
