// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart" show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB-j7SjQkt-ZD1Qce72qkT-pcdWwWmLuW8",
    appId: "1:664022703356:web:056e03f9499b7b60f78b79",
    messagingSenderId: "664022703356",
    projectId: "the-hill-residence",
    authDomain: "the-hill-residence.firebaseapp.com",
    storageBucket: "the-hill-residence.appspot.com",
    measurementId: "G-X6FWSFM4B2",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB5bisuEn3TcOjIp2DdI3Ay4o7XIQNHFik",
    appId: "1:664022703356:android:c54bbeba72c7f1bef78b79",
    messagingSenderId: "664022703356",
    projectId: "the-hill-residence",
    storageBucket: "the-hill-residence.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCV6IbFCGzq10f18lKbW0x8EaRS31LXhnI",
    appId: "1:664022703356:ios:159b7b679f6a7711f78b79",
    messagingSenderId: "664022703356",
    projectId: "the-hill-residence",
    storageBucket: "the-hill-residence.appspot.com",
    iosClientId: "664022703356-3b004kjjbkgd633evs84a2nvfofmmjrn.apps.googleusercontent.com",
    iosBundleId: "com.example.testing",
  );
}
